name: Fantasy Baseball Assistant

on:
  workflow_dispatch:

jobs:
  export:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

- name: Run Export
  env:
    ESPN_S2: ${{ secrets.ESPN_S2 }}
    SWID: ${{ secrets.SWID }}
  run: |
    python export.py
    python inspect.py

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: fantasy-export
          path: exports/
